language: node_js
node_js:
  - '4.1'
cache:
directories:
  - node_modules
deploy:
  api_key:
    secure: QNOeL/Ul7qCl7wqTWmn2pax+m6b7JcyoY9XX+3RkS8OAU1mZ8e+8p9TdazDZVfAh6HiSFzUsK79f0w0cERLpXRXUH4tE5o6dnhGrAfui/cESP1eD7QlrJh+vegvurAMFUhmNPlE9zHTVVLhpKNC1FqXkvVn5f6rf4uA8VtyZQk5y5HSMC1pV7R5zRw3gIPpIZxcpq9PlS+AjrPy22pG+KKMD7veKOacP12kUzQFk628avrc6qhMa1DJmceOAPWlSRPYE8nj5FA4liPFGTQrex/nZQNmY9m8MwpnoviYpUx5ZD9K/8vNi1fp8bqh443L6cmKJehnI16fwWXBUzafdEm26urZPA7EZFEj1VCLmumEpcLoAoyxYSUJiY20cKfPat730F226ncp5l9hxlSvnpuOxHlTQDiwsz1vvg6Lz+ikkGECkfDPTEBBFo/hxU3E1iXDptCb+lQoXerbddlcJVMmYA10vUvK+/FcHQC0D8Jv/gt2QtgBDIwFKFv4+8Ayc3lbb87NO04JggSsfNYqLqTXSfD6vqlW0/mAxj5vVihpBJ9M9YaxF6oMWzQ5vwSVKhvCVxlSZMO0r6MYcmuaqW0RX35RZBna/Ctts+H2GMOhARqZpKuQ9MlCvldSJEWm5aqB+P5gb0iI76veUJop8lJnnzHe27CFZNjbUbAPR5VM=
