language: node_js
node_js:
- '4'
cache: 
directories:
- node_modules
deploy:
  provider: heroku
  app: tsuyoku-web
  on:
    repo: jrogozen/tsuyoku-web
  api_key:
    secure: gxnAcKWpsYxmI94Y8t3fJRNZqXTeZVRullHqpUGHrQat5bKAmGf4jIIOklybpADfxP3xp462GcvDZuX8TnilY/qzcPMIGB21oCyvEDSHIeEWp2xYYqHm7shPp9xOA+17WzonQupT4nv1P01+DAwbax3ewJw/Tw3P1H/VZ2eICzPuZGe1UkJ8qZVmE9NVP4zoWpeDzh8h+BWcKzG16vb45jbwyrXuksKps4zoZL7nSyjPTvnki+5U/JOfzgrAg49itWOnNfNE7hA5IXLxKl29wH5ioCJwdSrflqJviYXlQQUAjfHUHRu8AAbRmhWcjO4ryHfp9zeZ7VBgZjjFxD72eSg25N3cqigPeiMAdLsegXRGtPsEVTaTPBJ18N2asvfDuLVRxJUKmKrvjAt4izWhxpIlW5gTzS+EqDn18ADAyHwzRPAAwhyufdbNHP3bkbirOH0PFo/cDVBprKWN3/SEBUtuIJe9FwTwnpn2MPbb1S34j9dhcpOXVCV6rmYOCKBSAaJD8GXNracp7MYwx2QEq3AEyzd5qZFU13O6govjivnF6RyqNxIfdGe2QS+4b/P96fdQEP/wkbOJGDfxgVKvVUTLbN9pJOaXiDaQDuaIUUDYHeFnPYFSCB3alDuQBSy2gN1xgN4oYBq0PTtlyQeHd0hoqa/345ENntcLf/6azm8=
