language: node_js
node_js:
- '4'
cache: 
directories:
- node_modules
deploy:
  provider: heroku
  app: tsuyoku-web
  on:
    repo: jrogozen/tsuyoku-web
  api_key:
    secure: o2ZJc4tShWGCzKCO+ePXkDOxKhd9AsId9ScZksmPm82htmqGQHwryujAKNWb63/oPrLDdD7Q5aIXFcROs8JMeQP0i6g29KaU8sK6FxPN3640pmcjcAHkdi9J+9dNrTxcNEN94I+zPxthmkEUbFeuAk18SHGMoLEQxtptCGbJnbHcrUVYmpFl+eZICTcffqigxPhNXxA4mj4F9WO+ja1OC7zmKR82/zlT4bWpe4jkIc1jGindCt8LVovpPK1lV0dBh5382zCLVNPNvH70Bv5FKNGzIHAhHhfyvZ/KPu3t5eWIvboVziIHeA4iZoVc+c+QzkhJFWEjcEJXy4dAinktt29aZT82yQV7vqHq9n+LyvS+IQ8/Z7m1p3qK6z+/cbG6suxDTeTYX9FFW5Z/LS5zv5JGOKXDHoP6ByVFsuv93djzyE0jIQ6ncdK2O3WIeC/Im9CbXMCGcSEjvC535SF3831LIiPekySRZxK9ieofW01CfqAw90z2P7j7IPoqmMCBn1TGujRcc7dQHe526wiBlIO+4pBPIbX8lIBDW4iuzCFwFfLtM1hGgPFjzWqs3FwO8RgNHNWzXS7tCtGu8b1JigYwtCTh1aFp1Wxg1hBBcej/WI6CXVuOW5sp907lLoXVq9v3FiUcVO7N1/4rYw78QDEqdKwRPR7CfM8TWqQjgJo=
